# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16881b285100b446790c29045c7d43fe84c9855984f53baa325da998f1bfea62bbbe055f644b6c9eafbb30585cafa408c637216a5a14031bef148599c9705598

test:
  secret_key_base: 7e9fecc0d79455ed4f89f5bdf80820e8214d5d1773d4c492da9849803d66ef47eecc2e88b538c6610d6212206c6a1e248b51d0c7450fde5678e5ac2289e519cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
